<?php

/**
 * @file
 * Contains entity_smile.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function entity_smile_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the entity_smile module.
    case 'help.page.entity_smile':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom module and entity by drupal console') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function entity_smile_theme() {
  return [
    'entity_smile' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_theme().
 */
function entity_smile_theme() {
  $theme = [];
  $theme['entity_smile'] = [
    'render element' => 'elements',
    'file' => 'entity_smile.page.inc',
    'template' => 'entity_smile',
  ];
  $theme['entity_smile_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'entity_smile.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function entity_smile_theme_suggestions_entity_smile(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#entity_smile'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'entity_smile__' . $sanitized_view_mode;
  $suggestions[] = 'entity_smile__' . $entity->bundle();
  $suggestions[] = 'entity_smile__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'entity_smile__' . $entity->id();
  $suggestions[] = 'entity_smile__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
